version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: muro_postgres
    environment:
      POSTGRES_DB: muro_dev
      POSTGRES_USER: muro_user
      POSTGRES_PASSWORD: muro_pass_2024
    ports:
      - "5432:5432"
    volumes:
      - muro_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U muro_user -d muro_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: muro_redis
    ports:
      - "6379:6379"
    volumes:
      - muro_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  muro_pgdata:
  muro_redisdata:
